name: clockify-kiss
summary: Simplify how time entries are filled in Clockify
description: |
  For further details go on: https://github.com/sebge2/clockify-kiss
version: '1.0.1'
apps:
  clockify-kiss:
    command: clockifyKiss
base: core18
parts:
  clockify-kiss:
    plugin: python
    source: .
plugs:
  clockify-kiss-home:
    interface: home
  clockify-kiss-network:
    interface: network
